### ISSUE TITLE
请问如何安装使用？

### ISSUE THREAD

**Issue by Holiday2019** [popyoung/History-FullText-Searcher#1]
浏览器开发小白。
请问应该如何安装这一脚本？

**Comment by Holiday2019** [comment]
已上线火狐扩展商店[历史搜索助手 – 下载 🦊 Firefox 扩展（zh-CN）](https://addons.mozilla.org/zh-CN/firefox/addon/%E5%8E%86%E5%8F%B2%E6%90%9C%E7%B4%A2%E5%8A%A9%E6%89%8B/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

**Comment by popyoung** [comment]
对，其实上传第一个版本的时候就上线了。我错误的以为过来的人都知道。
